server:
  port: 8188
spring:
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 1
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiangstudy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
netty:
  port: 18080